name: knapsack-gnn
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      # Install from requirements.txt (CPU version by default)
      - -r requirements.txt
      # Optionally install dev dependencies
      # - -r requirements-dev.txt
